### ISSUE TITLE
Occasional error in code leads to 'Error: 500 Internal Server Error'

### ISSUE THREAD

**Issue by flawiddsouza** [captn3m0/indiapost-tracker#2]
Sometimes when getting the tracking info, I get this error:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "web.py", line 22, in track
    details = Tracker().track(id)
  File "E:\indiapost-tracker\tracker.py", line 49, in track
    general_details = dom.find(id="GridView1").findAll('td')
```

Refreshing the page rectifies it but what could be causing it?

**Comment by captn3m0** [comment]
I think there should be an error message before the Traceback. Can you share that as well?

**Comment by flawiddsouza** [comment]
Sorry, here:
`AttributeError: 'NoneType' object has no attribute 'findAll'`

**Comment by captn3m0** [comment]
That probably means that Speed Post is either not returning the HTML that I expect, or that they changed the html itself. Since you say refreshing it fixes it, it might be that India Post is giving intermittent invalid pages.

**Comment by flawiddsouza** [comment]
Probably it, though returning an error in JSON saying "The request failed" or something would be cool.

**Comment by captn3m0** [comment]
@hornedbull: Any thoughts on this?

**Comment by vatsalshah1990** [comment]
I think we can raise a custom value error with a message of "awb not found". Because this happens when the Dom doesn't have any elements due to an incorrect tracking number or a tracking number which is not in the system yet.

If you think that the right way, I can push an update to the code.
- Vatsal

**Comment by captn3m0** [comment]
Added a try/catch for this in #8, closing
