### ISSUE TITLE
Implementing registered post tracking

### ISSUE THREAD

**Issue by krishnamuppaneni** [captn3m0/indiapost-tracker#3]
Hey, I was able to successfully implement the registered post tracking. I simply replicated the functionality of speed post tracking on this url: http://indiapost.gov.in/rnettracking.aspx

**Comment by captn3m0** [comment]
Cool. Wanna file a PR?

**Comment by krishnamuppaneni** [comment]
Sure...

**Comment by captn3m0** [comment]
Cool. I'll add you to the collaborators once we merge it.
