### ISSUE TITLE
Changes in IndiaPost website

### ISSUE THREAD

**Issue by nishad** [captn3m0/indiapost-tracker#6]
Its a wonderful attempt, and relay useful.
With the recent changes in IndiaPost website, this api fails to operate. 
Any possible workarounds?

**Comment by krutiparanthi** [comment]
same here. not working properly. pls. advice.
my url https://www.greeninterio.com/track-order-status/

**Comment by captn3m0** [comment]
This isn't maintained anymore., due the many changes that india-post has made at their end.

If you'd be interested in taking this up, please reply, and I'll add you to the collaborators.

**Comment by captn3m0** [comment]
Works with new India Post system now (#8, merging soon)
