### ISSUE TITLE
Application Crashing - Change in Speed Post HTML Table Name

### ISSUE THREAD

**Issue by che2on** [captn3m0/indiapost-tracker#9]
Hi,

I wanted to bring it to your notice that this application is not working anymore. It was working 4 months back... it was very helpful.

There is a change in speed post interface - the responsive table has been now renamed to a different class and also the number of table columns changes dynamically... It will be great if you can fix few lines in tracker.py

I modified following lines by commenting it out - however, it is still crashing! I am new to python. 

```
   try:
            general_details = dom.find(id=ARTICLE_DETAILS_ID).findAll('td')
            details = {'id': id,
                       'origin': general_details[0].text.strip(),
                       #'booking_date': parser.parse(general_details[1].text.strip()),
                       'pincode': general_details[2].text.strip(),
                       'tariff': general_details[3].text.strip(),
                       'category': general_details[4].text.strip(),
                       'destination': general_details[5].text.strip(),
                       #'delivery_date': general_details[6].text.strip()
                       }
            #details['delivered'] = details['delivery_date'] != 'Not Available'

            details['events'] = []

            #events = dom.find(class_='responsivetable MailArticleEvnt').findAll('tr')[1:]
            events = dom.find(class_='responsivetable MailArticleEvntOER').findAll('tr')[1:]
            for tr in events:
                event = {}
                data = tr.findAll('td')
                event['date'] = parser.parse(data[0].text.strip() + ' ' + data[1].text.strip() + ' IST')

        self.POST_DATA["ctl00$PlaceHolderMain$ucOERControl$txtOrignlPgTranNo"] = id
        response = requests.post(TRACKING_URL, data=self.POST_DATA)
        dom = BeautifulSoup(response.content, "html.parser")
```

Will be great if you can fix it please @captn3m0 @vatsalshah1990 .

**Comment by vatsalshah1990** [comment]
Can you please create a PR with the fix?

**Comment by che2on** [comment]
Sorry, I don't know Python. If you can look for about 15 minutes it will be nice. Thank you. @vatsalshah1990 @captn3m0

**Comment by captn3m0** [comment]
This is now resolved. I've only found time to test and fix the normal flow (not the international package website).

Added nightly tests, so I'll get a notification the next time this breaks.

See https://india-post-tracker-api.herokuapp.com/track/EO430454377IN for a working request.

**Comment by che2on** [comment]
Perfect. This is working now. Thanks a lot @captn3m0

**Comment by captn3m0** [comment]
Just notifying here that this is broken again, because IndiaPost is now breaking the saved request state by some backend logic.

Earlier, this would do a replay attack by giving the same captcha response, but now it breaks after some time (N requests from a session perhaps? or maybe 24 hours). Need to think of a smarter way that relies on anyone solving a captcha once every 24 hours maybe?

**Comment by che2on** [comment]
For your information - The Captcha is not always to type the letters. There are multiple other challenges like
1. Enter characters as displayed in image
2. Enter the Second number/character in Captcha
3. Evaluate the Expression (Eg 4+3) etc
@captn3m0

**Comment by captn3m0** [comment]
I'm aware of this.

Just haven't had time to see if breaking it again is a good idea (the 2015 version of the app used to do that)
